details:
  namespace: student50-details-dev
  image: ghcr.io/wavemoroc001/details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-details
  port: 8080
  healthCheckPath: "/health"

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
      # kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/ssl-redirect: "false"
  host: final.porplatakkom.com
  path: "/student50(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
