ratings:
  namespace: student50-bookinfo-dev
  image: ghcr.io/wavemoroc001/details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-details
  port: 8080
  healthCheckPath: "/health"

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.dev.opsta.net
  path: "/student50/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
