name: Ruby Gem

on:
  push:
    branches: [ dev,master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - name: set up env
      run: echo "ENV_NAME=$( [ "$GITHUB_REF" == "refs/heads/master" ] && echo 'uat' || echo ${GITHUB_REF##*/} )" >> $GITHUB_ENV
    
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5'
        
#     - name: Test & Build Ruby
#       run: gem install bundler
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ghcr.io/wavemoroc001/details:${{ env.ENV_NAME }}

